### ISSUE TITLE
Windows testing...

### ISSUE THREAD

**Issue by moebiussurfing** [roymacdonald/ofxWhisper#2]
Hey, 
I am getting this error: 
dr_wav.h': No such file or directory	
```.bash
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'dr_wav.h': No such file or directory	example	C:\Users\moebi\OneDrive\Documents\openFrameworks\addons\ofxWhisper\libs\whisper_cpp\src\common.cpp	6	
```
 
Maybe it's bc it requires the lib compile mentioned on [ofxSampleRate](https://github.com/roymacdonald/ofxSampleRate)?
```
Compatibility

Currently only the macos compiled library of libsamplerate is included with this addon. If you want to use on another OS, please add the appropriate pre compiled static library to the libs/libsamplerate/lib/<your system type> folder.
```

PS:
Also I edited the sh script with the `win` rename, but it created the `osx` folder again when running it.

**Comment by roymacdonald** [comment]
HI. Oh, no dr_wav is for reading the wav files but I did not include it and forgot to remove the function that uses it (which I took out from the example I used to make this).
I think that the lib folder should be vs rather than win. I will check that and I can add to the script.
Thanks for testing

**Comment by roymacdonald** [comment]
ok. I fixed this although I have not tested on windows yet

**Comment by moebiussurfing** [comment]
sh script said some error but it closed fast...
EDIT: I can't take a screenshot but says something about .a file not found

I downloaded the sampleRate release .lib/.dll just in case.
https://github.com/libsndfile/libsamplerate/releases/tag/0.2.2

Now I am getting this:

![image](https://user-images.githubusercontent.com/2106149/222988859-0ee4d15c-7b13-493c-927b-87e0b9e09c90.png)

**Comment by moebiussurfing** [comment]
btw PG do not added the samplerate.lib file to the project...

**Comment by moebiussurfing** [comment]
![image](https://user-images.githubusercontent.com/2106149/222989386-fde71b0a-b7a8-4930-a7b7-a4ab13c23e9a.png)

**Comment by roymacdonald** [comment]
I see. probably needs to be set in the addon_config file.
Did you get it to work?
all the errors you are getting are because the libraries are not being linked

**Comment by moebiussurfing** [comment]
not working

**Comment by moebiussurfing** [comment]
I tried to add manually the .lib on the VS linker property page but no success

**Comment by roymacdonald** [comment]
Hi @moebiussurfing I just pushed an update to the build_lib.sh script for windows. Using it I am able to compile and run with no problems or extra setups on Visual Studio 2022

**Comment by moebiussurfing** [comment]
I pulled also ofxSampleRate but now having these errors:

![image](https://user-images.githubusercontent.com/2106149/223334945-8bd17af4-83d3-41c3-98c8-c7e37635b8ef.png)

**Comment by roymacdonald** [comment]
I think you are running on debug and the built lib is release only

**Comment by moebiussurfing** [comment]
when compiling using release it works, 
I need to open the exe as administrator.

but models path seams broken:

![image](https://user-images.githubusercontent.com/2106149/223489131-a70d930e-2393-436b-973d-f1c92512b2b9.png)

Then copied models/ into bin/data and it worked:

![image](https://user-images.githubusercontent.com/2106149/223490237-518da19f-c637-4d7a-97f7-91aae526da0c.png)

**Comment by moebiussurfing** [comment]
![image](https://user-images.githubusercontent.com/2106149/223491461-567820a3-74bd-434b-a4b6-2fb1757f6d36.png)
Run as admin:
Go to Linker > All Options and set UAC Execution Level to Require Administrartor

**Comment by moebiussurfing** [comment]
awesome!

![image](https://user-images.githubusercontent.com/2106149/223492647-14406766-af5f-474c-8224-501601db2cec.png)

**Comment by roymacdonald** [comment]
great, I did not need to run as admin to make it work though.

**Comment by moebiussurfing** [comment]
Do you know if Debug should work?
I edited the .sh script from Release->Debug, generated a new .lib with the same name
but then it compiled on Debug but it didn't generated text.

**Comment by roymacdonald** [comment]
i have not tried it in debug mode

**Comment by moebiussurfing** [comment]
sorry, it worked on Debug, but required regenerate with PG
